/**
 * Cross-implementation check for `naddr` encoding.
 *
 * The expected string below is not hand-computed: it is what Linear-lite's own
 * independent `addrToNaddr` produces for the same address. Peek grew an encoder
 * when the sidebar had to hand objects back out (PEEK-24) — a link into the
 * owning app, and an action addressed to a record — and an encoder that is
 * merely self-consistent would be worthless: the whole claim is that two apps
 * agreeing on a wire format can work on the same data.
 *
 * So if this fails, do not regenerate the expected value. Find what changed in
 * the TLV order, the checksum constant, or the padding.
 */
import { describe, it } from 'node:test'
import assert from 'node:assert/strict'
import { decodeNaddr, encodeNaddr, findNaddrs, pointerToAddress, stripNaddrs } from '../dist/index.js'

const PUBKEY = 'b3'.repeat(32)
const IDENTIFIER = 'a742e679-ca8c-488e-8d60-9836cc81bde2'

describe('encodeNaddr', () => {
  it('produces what Linear-lite produces for the same address', () => {
    assert.equal(encodeNaddr({
        kind: 30851,
        pubkey: PUBKEY,
        identifier: IDENTIFIER,
        relays: ['http://localhost:3000'],
      }), 'naddr1qqjxzde5xfjnvdee943kzwrr956rswr995uxgd3s95unsvekvd3nsvtzv3jnyqg4dp68gup69uhkc' +
        'mmrv9kxsmmnwsarxvpsxqpzpvankwem8vankwem8vankwem8vankwem8vankwem8vankwem8vanqvzqqqrcsvczkget')
  })

  it('round-trips through the decoder, relay hints and all', () => {
    const pointer = { kind: 30850, pubkey: PUBKEY, identifier: 'p1', relays: ['wss://relay.example'] }

    assert.deepEqual(decodeNaddr(encodeNaddr(pointer)), pointer)
  })

  it('round-trips an address with no relay hint', () => {
    const pointer = { kind: 30851, pubkey: PUBKEY, identifier: IDENTIFIER, relays: [] }

    assert.equal(pointerToAddress(decodeNaddr(encodeNaddr(pointer))), `30851:${PUBKEY}:${IDENTIFIER}`)
  })

  it('refuses a pubkey that is not 32 bytes', () => {
    assert.throws(() => encodeNaddr({ kind: 1, pubkey: 'abcd', identifier: 'x', relays: [] }), /32 bytes/)
  })
})

describe('Ship paste contract', () => {
  // Generated by Ship's independent addrToNaddr implementation, including the
  // relay hint Ship places on the clipboard value.
  const SHIP_REFERENCE =
    'nostr:naddr1qqjxzde5xfjnvdee943kzwrr956rswr995uxgd3s95unsvekvd3nsvtzv3jnyqg4dp68gup69uhkc' +
    'mmrv9kxsmmnwsarxvpsxqpzpvankwem8vankwem8vankwem8vankwem8vankwem8vankwem8vanqvzqqqrcsvczkget'

  it('finds and decodes the exact reference Ship puts on the clipboard', () => {
    const [naddr] = findNaddrs(`Please take this issue: ${SHIP_REFERENCE}`)
    assert.equal(naddr, SHIP_REFERENCE.slice('nostr:'.length))
    assert.equal(pointerToAddress(decodeNaddr(naddr)), `30851:${PUBKEY}:${IDENTIFIER}`)
  })
})

/**
 * PEEK-18: the pointer becomes a widget, so it leaves the prose.
 *
 * The cases that matter are all about what is left *behind* — a reference is
 * removed from the middle of a sentence, off the end of one, or from a line of
 * its own, and each leaves different debris.
 */
describe('stripNaddrs', () => {
  const REF = `nostr:${encodeNaddr({ kind: 30851, pubkey: PUBKEY, identifier: IDENTIFIER, relays: [] })}`

  it('takes the pointer off the end without leaving trailing space', () => {
    assert.equal(stripNaddrs(`Picking this up today ${REF}`), 'Picking this up today')
  })

  it('closes the gap when the pointer was mid-sentence', () => {
    assert.equal(stripNaddrs(`See ${REF} for the details.`), 'See for the details.')
  })

  it('does not leave a hole where a pointer had its own line', () => {
    assert.equal(stripNaddrs(`Shipping today.\n\n${REF}\n\nLet me know.`), 'Shipping today.\n\nLet me know.')
  })

  it('reduces a message that was only a pointer to nothing', () => {
    // The caller uses this to skip the paragraph entirely rather than render an
    // empty one that still takes up a gap.
    assert.equal(stripNaddrs(REF), '')
  })

  it('removes every pointer, not just the first', () => {
    assert.equal(stripNaddrs(`${REF} and ${REF}`), 'and')
  })

  it('keeps paragraph breaks and indentation in text that has no pointer', () => {
    const body = 'One\n\n  two\nthree'
    assert.equal(stripNaddrs(body), body)
  })
})
